#!/usr/bin/env python3
"""Generates Core/Sources/FieldnoteKit/ModelCatalogData.swift: the optional model
downloads, pinned to exact Hugging Face revisions, with every file's size and
SHA-256.

The app downloads these only when the user taps Download, from these revisions
only, and rejects any file whose hash doesn't match. Bumping a revision is a
deliberate, reviewed change: edit PACKS below and re-run this script.

    Scripts/build-model-manifest.py

LFS files carry their SHA-256 in the Hugging Face API; small non-LFS files
(model.mil, JSON) are downloaded and hashed here.
"""
import hashlib
import json
import os
import urllib.request

PACKS = [
    {
        "id": "parakeetV3",
        "name": "Parakeet TDT v3 (NVIDIA)",
        "repo": "FluidInference/parakeet-tdt-0.6b-v3-coreml",
        "revision": "7dd20fe6b1797d35f5e3307e8b1732d9a178edfe",
        "license": "CC-BY-4.0",
        # FluidAudio's v3 file set with the default 6-bit encoder: int4 roughly
        # doubles WER and is slower (FluidAudio EncoderComputePlacement.md).
        "paths": ["Preprocessor.mlmodelc", "Encoder.mlmodelc", "Decoder.mlmodelc",
                  "JointDecisionv3.mlmodelc", "parakeet_vocab.json"],
    },
    {
        "id": "pyannoteCommunity1",
        "name": "pyannote community-1",
        "repo": "FluidInference/speaker-diarization-coreml",
        "revision": "1ed7a662fdc7109e36d822db793ee6eebdaf8594",
        "license": "CC-BY-4.0",
        "paths": ["Segmentation.mlmodelc", "FBank.mlmodelc", "Embedding.mlmodelc",
                  "PldaRho.mlmodelc", "plda-parameters.json"],
    },
    {
        "id": "pyannoteLegacy",
        "name": "pyannote 3.1 (legacy)",
        "repo": "FluidInference/speaker-diarization-coreml",
        "revision": "1ed7a662fdc7109e36d822db793ee6eebdaf8594",
        "license": "CC-BY-4.0",
        "paths": ["pyannote_segmentation.mlmodelc", "wespeaker_v2.mlmodelc"],
    },
]


def api(url):
    with urllib.request.urlopen(url) as response:
        return json.load(response)


def tree(repo, revision, path):
    entries = api(f"https://huggingface.co/api/models/{repo}/tree/{revision}/{path}?recursive=true")
    return [e for e in entries if e["type"] == "file"]


def files_for(pack):
    out = []
    for path in pack["paths"]:
        if path.endswith(".json"):
            entries = [e for e in api(f"https://huggingface.co/api/models/{pack['repo']}/tree/{pack['revision']}")
                       if e["path"] == path]
        else:
            entries = tree(pack["repo"], pack["revision"], path)
        for entry in entries:
            if "lfs" in entry and entry["lfs"]:
                sha = entry["lfs"]["oid"]
                size = entry["lfs"]["size"]
            else:
                url = f"https://huggingface.co/{pack['repo']}/resolve/{pack['revision']}/{entry['path']}"
                data = urllib.request.urlopen(url).read()
                sha = hashlib.sha256(data).hexdigest()
                size = len(data)
            out.append((entry["path"], size, sha))
    return sorted(out)


def swift_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = [
    "// Generated by Scripts/build-model-manifest.py. Do not edit by hand.",
    "",
    "extension ModelPack {",
    "    public static let catalog: [ModelPack] = [",
]
for pack in PACKS:
    files = files_for(pack)
    total = sum(size for _, size, _ in files)
    print(f"{pack['id']}: {len(files)} files, {total / 1e6:.1f} MB")
    lines += [
        "        ModelPack(",
        f"            id: .{pack['id']},",
        f"            name: {swift_string(pack['name'])},",
        f"            repo: {swift_string(pack['repo'])},",
        f"            revision: {swift_string(pack['revision'])},",
        f"            license: {swift_string(pack['license'])},",
        "            files: [",
    ]
    for path, size, sha in files:
        lines.append(f"                ModelFile(path: {swift_string(path)}, size: {size}, sha256: {swift_string(sha)}),")
    lines += ["            ]", "        ),"]
lines += ["    ]", "}", ""]

out = os.path.join(os.path.dirname(__file__), "..", "Core", "Sources", "FieldnoteKit", "ModelCatalogData.swift")
with open(out, "w") as f:
    f.write("\n".join(lines))
print("wrote", os.path.normpath(out))
